# Generated by Django 2.2.6 on 2019-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'USER'), ('PARTNER', 'PARTNER')], default='USER', max_length=10),
        ),
    ]
